# Este nodo funciona como Worker
coordinator=false

# Puerto interno de Presto
http-server.http.port=8080

# Memoria máxima total para consultas
query.max-memory=512MB

# Memoria máxima asignada por nodo
query.max-memory-per-node=128MB

# Dirección del coordinator del clúster
discovery.uri=http://coordinator:8080