# Este nodo actuará como el Coordinator del clúster
coordinator=true

# Evita que el coordinator procese consultas pesadas
# Solo coordina el trabajo entre workers
node-scheduler.include-coordinator=false

# Puerto HTTP de Presto
http-server.http.port=8080

# Memoria máxima total permitida para consultas
query.max-memory=1GB

# Memoria máxima por nodo
query.max-memory-per-node=512MB

# Activa el servicio de descubrimiento de nodos
discovery-server.enabled=true

# URL del coordinator para que workers se conecten
discovery.uri=http://coordinator:8080