# Hive connector para archivos Parquet
connector.name=hive-hadoop2

# Metastore local basado en archivos
hive.metastore=file

# Ruta del Data Lake montado en Docker
hive.metastore.catalog.dir=file:///data-lake/parquet