# Connector PostgreSQL
connector.name=postgresql

# URL JDBC interna Docker
connection-url=jdbc:postgresql://postgres-db:5432/medioambiente

# Usuario PostgreSQL
connection-user=admin

# Contraseña PostgreSQL
connection-password=admin