# Este nodo actuará como Coordinator del clúster
coordinator=true

# Evita que el coordinator procese consultas pesadas
# Solo coordina el trabajo entre workers
node-scheduler.include-coordinator=true

# Puerto HTTP de Presto
http-server.http.port=8080

# Memoria máxima total permitida para consultas
query.max-memory=512MB

# Memoria máxima por nodo
query.max-memory-per-node=128MB

# Activa el servicio de descubrimiento de nodos
discovery-server.enabled=true

# URL del coordinator para que workers se conecten
discovery.uri=http://presto-coordinator:8080